### ISSUE TITLE
7. Send Emails

### ISSUE THREAD

**Issue by LucHighwalker** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#11]
broken mailgun link, one too many w's

**Comment by LucHighwalker** [comment]
in the 'MAKE A MAILGUN ACCOUNT & ADD CREDENTIALS' section

**Comment by ibirnam** [comment]
Good catch, fixed in 6ebc645c40064f7315d1f0ea832091a74dc4cd7a
