### ISSUE TITLE
7. Send Emails

### ISSUE THREAD

**Issue by JSitter** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#12]
Send an Email When Pets are Purchased.

Sample code blocks showing code for the route '/pets/:id/purchase' may not be rendering correctly. Code is split across different code and block quote blocks. 

A snippet "}); ```" exists as part of the explanatory text immediately after these blocks.

**Comment by ibirnam** [comment]
So sorry about that! Should've caught that before I pushed that up yesterday, fixed now in ff06e26df35caa216da28472d50a3cc91b8b7c1a and is live on the tutorial site.
