### ISSUE TITLE
6. Payment Gateways: Stripe

### ISSUE THREAD

**Issue by campbellmarianna** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#13]
In the Customizing The Checkout Widget section, I created a purchase pet route and typed the code below :
`
app.post('/pets/:id/purchase', (req,res) => {
  console.log("purchase body:", ${req.body});
});
`
After, my app crashed and I encountered a SyntaxError. A fellow software engineering student @StephanieCherubin shared with me that since I had the dollar sign and curly braces I needed templates strings. Once I added a template string (example below) my app was running and I could continue.

`
    app.post("/pets/:id/purchase", (req, res) => {
        console.log(`purchase body: ${req.body}`);
    });
`

**Comment by ibirnam** [comment]
Great find @campbellmarianna and @StephanieCherubin ! Sorry for the issue there, fixed in  786a34baf67b6c0dbe1cf42d541d15301926e97c, and update should be live on the tutorial now as well
