### ISSUE TITLE
4. Validation, Success, and Error Handling - Typo #2

### ISSUE THREAD

**Issue by timkaing** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#2]
File Path does not match the starter project

Preexisting action:
> Replace the current `create` route in `/controllers/pets.js` with the following:

Should be:
> Replace the current `create` route in `/routes/pets.js` with the following:

**Comment by ibirnam** [comment]
Fixed in 209627275051287a154a907221212aaf90a097b4
