### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ryanlsmith4** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#5]
On the pagination part unless you put a search term in it doesn't scroll through the pets...

**Comment by ibirnam** [comment]
@ryanlsmith4 can you be more specific on the exact issue you're having? which section on the Pagination page are you working on? Are you saying pagination does not work on the home screen, but it only works when you search?

**Comment by ryanlsmith4** [comment]
Yes that's what I ment.

**Comment by ibirnam** [comment]
Read the `Page Parameter` section of the chapter again and look carefully at the update to `/routes/index.js` and see what's missing from your code.

Once you fix the code, see if that fixes the issue, and comment here if it does/doesn't

**Comment by ibirnam** [comment]
Closing for the same reasoning as  https://github.com/MakeSchool-Tutorials/Proud-Petes-Pet-Emporium/issues/6#issuecomment-458209846

Slack me if you have more questions. Thanks!
