### ISSUE TITLE
5. Uploading Files to AWS S3

### ISSUE THREAD

**Issue by ryanlsmith4** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#6]
On this portion of the tutorial I've noticed my new information is being saved but it's not being presented on the views..
<img width="946" alt="screen shot 2019-01-26 at 3 30 16 pm" src="https://user-images.githubusercontent.com/36646424/51794048-6a548d00-217f-11e9-99b8-0a2e4cc4aaf3.png">

**Comment by ibirnam** [comment]
@ryanlsmith4 - there's a lot of different things that could be causing this, have you checked the following from the tutorial?

- Made sure `imagemagick` is installed?
- you have all the correct code in `/routes/pets.js`?
- You updated `public/javascripts/scripts.js`?
- You updated `models/pet.js`?
- You updated all your `views` appropriately, remembering to use a `.` after `-standard` and `-square`? That one is easy to miss

Finally, you should also open up chrome tools and check the console logs to see if you're getting a particular error. that may help debug this

**Comment by ryanlsmith4** [comment]
I'm quite sure all my code is verbatim.  I also checked dev tools. No
errors.  I'm new with pug but i'm fairly confident my code matches the
tutorial.  With that said please check my github and tell me if i'm off.  I
must be missing something but can't tell.

**Comment by ibirnam** [comment]
`pets-index.pug` line 9, you have `pet.avatarUrl` in double quotes:
`img.card-img-top(src="pet.avatarUrl" + '-standard.', alt="Card image cap")`

when you need to drop the double quotes:
`img.card-img-top(src=pet.avatarUrl + '-standard.', alt="Card image cap")`

Try that and see if that fixes it

**Comment by ibirnam** [comment]
Comment here if it does or doesn't fix it

**Comment by ryanlsmith4** [comment]
I still lack the ability to use the edit button. But that did fix the
visual problem. This portion is a bit wonky but  i apologize for not
noticing the quotes.
V/R
Ryan Lee Smith

**Comment by ryanlsmith4** [comment]
the new items not the old. I changed it to ${pet.name} and that didn't make
it dynamic instead it was string literal the #{pet.name} works but not
bringing the new stuff to screen
V/R
Ryan Lee Smith

**Comment by ryanlsmith4** [comment]
But also the pet index page doesn't paginate unless you search.
V/R
Ryan Lee Smith

**Comment by ryanlsmith4** [comment]
I'm using es6 functions on the route but... There is no implicit this so it
should work correctly?
V/R
Ryan Lee Smith

**Comment by ibirnam** [comment]
@ryanlsmith4 - at this point it would probably be best to seek help with this at office hours, or through some other in-person debugging capacity.

The github issues are for if you find errors in the tutorial (i.e. typos, invalid/incorrect code, etc.), or suggestions for improvements. If you discover an erroneous part of the tutorial than please make the issue here, but not for just debugging purposes.

I'm going to close out this issue, but feel free to DM me on slack if you have additional questions
