### ISSUE TITLE
6. Payment Gateways: Stripe

### ISSUE THREAD

**Issue by nsafai** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#7]
I think 
```
form(action=`/pets/${pet._id}/purchase`, method='POST')
```
should be:
```
form(action=`/pets/${pet.id}/purchase`, method='POST')
```

The underscore doesn't seem supported by PUG

**Comment by ibirnam** [comment]
@nsafai - I'm using the underscore in my solution and it's working fine, what error are you getting?

**Comment by nsafai** [comment]
you know what? its working with the underscore for me too. I must have made another fix at the same time and diagnosed the root cause incorrectly.
