### ISSUE TITLE
6. Payment Gateways: Stripe

### ISSUE THREAD

**Issue by ryanlsmith4** [MakeSchool-Tutorials/Proud-Petes-Pet-Emporium#8]
Pet.findById(req.body.petId).exec(err pet) => {
 
Should be 
Pet.findById(req.body.petId).then((pet) => {
as the .exec cant use .catch

**Comment by ibirnam** [comment]
good catch (pun intended), but `findById` will break if we use `then` instead of `exec`, but we can still catch the error upfront using an [if statement](https://stackoverflow.com/questions/41896865/proper-error-handling-in-mongoose-query-exec).

Updated in 831425cd94cba3a288ebf969011e846362fb3141
